### ISSUE TITLE
PostgreSQL installation fails on Rocky 8 / RHEL 9

### ISSUE THREAD

**Issue by p-j-smith** [UCL-MIRSG/xnat-aws#20]
Installation fails with the error:

```
TASK [mirsg.postgresql : Ensure postgres RPM is installed] ******************************************************************************
fatal: [xnat_db]: FAILED! => {"changed": false, "msg": "Failed to validate GPG signature for pgdg-redhat-repo-42.0-32.noarch: Public key for pgdg-redhat-repo-latest.noarch7h0_duds.rpm is not installed"}
```

The [GPG key](https://github.com/UCL-MIRSG/xnat-aws/blob/c8a352221c8d1d96ee016658851daa9eb7f1ec30/configure/group_vars/all/vars/postgresql.yml#L13) needs to be imported:

```yaml
ansible.builtin.rpm_key:
  state: present
  key: "{{ postgresql_rpm_gpg_key_pgdg }}"
```
